version: '3.5'

services: 
    nginx:
        image: nginx:alpine
        container_name: ${PROJECT_NAME}-nginx
        ports: 
            - '5080:80'
        volumes: 
            - ./code:/code
            - ./docker/nginx/vhost:/etc/nginx/conf.d/default.conf
        links: 
            - php
    php:
        build:
            context: ./docker/php # 在这个位置找 Dockerfile
        container_name: ${PROJECT_NAME}-php
        ports: 
            - '9000:9000'
        volumes: 
            - ./code:/code