version: '3.5'

services: 
    nginx:
        image: nginx:alpine
        container_name: ${PROJECT_NAME}-nginx
        ports: 
            - '5080:80'
        volumes: 
            - ./code:/code
            - ./docker/nginx/vhost:/etc/nginx/conf.d/default.conf
            - ./logs/nginx/error.log:/var/log/nginx/error_manual.log
            - ./logs/nginx/access.log:/var/log/nginx/access_manual.log
        links: 
            - php
            - mysql
    php:
        build:
            context: ./docker/php # 在这个位置找 Dockerfile
            args: 
                XDEBUG_PORT: ${XDEBUG_PORT}
                XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY}
                XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
        image: php:alpine
        container_name: ${PROJECT_NAME}-php
        
        ports: 
            - '9000:9000'
        volumes: 
            - ./code:/code
            - ./docker/php/php.ini-${PHP_FPM_CONF}:/usr/local/etc/php/php.ini
            - ./logs/php/errors.log:/var/log/php-fpm/errors.log

    mysql:
        build: 
            context: ./docker/mysql
        image: 'mysql:5.7'
        container_name: ${PROJECT_NAME}-mysql
        environment: 
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports: 
            - '3306:3306'
        volumes: 
            - ./logs/mysql/mysqld.log:/var/log/mysqld.log

    redis:
        build:
            context: ./docker/redis
        image: 'redis:alpine'
        container_name: ${PROJECT_NAME}-redis
        ports:
            - '6379:6379'
        volumes: 
            - ./logs/redis/errors.log:/var/log/redis/errors.log